from langchain.prompts import PromptTemplate

template = """This is a question-answering system over a corpus of PDF documents.
The documents include both US and international IT compliance regulations.

Given chunks from multiple documents and a question, create an answer to the question that references those documents as "SOURCES".

- If the question asks about the system's capabilities, the system should respond with some version of "This system can answer questions based on defined set of IT compliance documents.". The answer does not need to include sources.
- If the answer cannot be determined from the chunks or from these instructions, the system should not answer the question. The system should instead return "The provided documents do not explicitly answer your question".
- Chunks are taken from the middle of documents and may be truncated or missing context.
- Documents are not guaranteed to be relevant to the question.
- Do not show full source URL in the answer. only document title.

QUESTION: How does SOC2 define the principle of Security?
=========
Content: Page 10 Description Criteria fn 10 Implementation Guidance  \n• Financial technology services.  Providing financial services companies with IT-based \ntransaction processing services . Examples of such transactions are loan processing, \npeer-to-peer lending, payment processing, retirement recordkeeping, crowdfunding, \nbig data analytics, and investment management. \n• Environmental, social, and go vernance (ESG) metric services . Measuring, calculating, \nand otherwise assisting companies with ga thering and reporting their ESG metrics. \nTo be useful to report users, the description should clearly identify the services that are the \nfocus of the SOC 2 examination.  \nWhen handling personal information, a service organization may functio n in the role of a \ndata processor, data controller , or both. Depending on which of these roles the service organi-\nzation performs, its responsibilities with rega rd to protecting persona l information may dif-\nfer. Therefore, when the SOC 2 examination addr esses privacy, clear disclo sure of the role or \nroles performed by the service or ganization may be necessary to  describe the types of ser-\nvices provided. Such disclosures enable user s to understand how the se rvice organization ad-\ndressed its responsibilities to mitigate risks to the achieveme nt of its service commitments \nand system requirements related to privacy.  \nDC2:  The principal service commitments and sys-\ntem requirements A service organization adopts a mission and vision, sets strategies, and es tablishes objectives \nto help it meet its mission a nd vision based on its strategies . Management designs and imple-\nments individual systems to achie ve specific objectives and desi gns and implements controls \nwithin the system to mitigate the risks that th reaten the service organi zation’s achievement of \nthose objectives. The service organization’s objectiv es for its services an d the system used to \ndeliver those services are embodied in the serv ice commitments it makes to user  entities and \nthe requirements it establishes for the functioning of the system used to deliver those services \n(service commitments and system requirements). Disclosure of the principal service commit-\nments and system requirements en ables report users to understand the obj ectives that drive
Title: 2018 SOC 2 Description Criteria

Content: AICPA Guide SOC 2® Reporting on an Examination of Controls at a Servi ce Organization Relevant to  Security, Availability, Pro-\ncessing Integrity, Confidentiality, or Privacy  uses the term service auditor , rather than practitioner , to refer to a CPA reporting on \ncontrols at a service organization. Therefore, this document also uses the term service auditor .  \nfn 5 There are two types of SOC 2 examinations (type 1 and type 2), and the subject matters vary depending on which type of exami-\nnation the service auditor performs. The subject matters of a type 1 examination are ( a) the description and ( b) the suitability of the \ndesign of the controls to provide reasonable assurance that th e service organization’s service co mmitments and system requireme nts \nwould be achieved based on the applicable trust services cr iteria. The subject matters in a type 2 examination are ( a) the description, \n(b) the suitability of design of the controls to provide reasonab le assurance that the service organization’s service commitments  and \nsystem requirements would be achieved based on the applicable trust services criteria, and ( c) the operating effectiveness of controls \nto provide reasonable assurance that the service organization’s service commitments and system requirements were achieved based  on \nthe applicable trust services criteria. \nfn 6  This term refers to the trust se rvices criteria in TSP section 100, 2017 Trust Services Criteria for Security, Availability, Pro-\ncessing Integrity, Confidentiality, and Privacy (With Revised Points of Focus — 2022) , that pertain to the category or categories in-\ncluded within the scope of the particular examination. \nfn 7 Paragraph .A44 of AT-C section 105, Concepts Common to All Attestation Engagements .
Title: 2018 SOC 2 Description Criteria

Content: Page 14 Description Criteria fn 10 Implementation Guidance  \nPrincipal service commitments  are those that support the und erstanding of the services pro-\nvided, the system, and the desi gn and operation of controls by a broad range of SOC 2 report \nusers.  \n• When a service organization makes the same system availability commitment to the ma-\njority of its user entities, it is likely that  management would disclose such commitments \nin the description because such informati on would support the understanding of a broad \nrange of SOC 2 report users.  \nWhen a service organization makes specific commit ments about system availability to one or \na small subset of user entities, management may decide to omit such commitments from the \ndescription because they are unlikely to suppor t the understanding of a broad range of SOC 2 \nreport users. In this situation, it is up to the individual user entity or  entities to obtain addi-\ntional information from the service organization re garding the achievement of specific availa-\nbility commitments. \nPrincipal system requirements  are those that are relevant to th e trust services category or cat-\negories addressed by the descripti on and that are likely to be re levant to the broad range of \nSOC 2 report users. In identify ing which system requirements to disclose, service organiza-\ntion management may consider in ternal policies that are relevant to the system being de-\nscribed, key decisions made in the design and operation of the system, and other business re-\nquirements for the system. For example, internal  requirements related to the operating margin \nfor the services associated with  the system are not relevant to  the broad range of SOC 2 re-\nport users and therefore n eed not be disclosed.  \nWhen the description addresses privacy, service organization management is likely to iden-\ntify the relevant service commitments and system  requirements identified in the service or-\nganization’s privacy notice or in its privacy po licy as part of its principal service commit-\nments and system requirements.  \nDC3:  The components of the system used to pro-\nvide the services, in cluding the following: \na. Infrastructure  Infrastructure.  Disclosures about the infrastructure component include ma tters such as the'
Title: 2018 SOC 2 Description Criteria
=========
FINAL ANSWER: The provided documents do not explicitly define the principle of Security as outlined by SOC2. They discuss aspects related to the examination of a service organization's controls over security, among other principles, and the importance of clear disclosures and descriptions in the context of SOC2 examinations. For a precise definition of the Security principle according to SOC2, one would need to refer directly to the SOC2 framework documentation or guidelines that specifically address the trust services criteria.
Title: 2018 SOC 2 Description Criteria

QUESTION: What are the five trust service principles of the SOC2 standard?
=========
Content: Page 10 Description Criteria fn 10 Implementation Guidance  \n• Financial technology services.  Providing financial services companies with IT-based \ntransaction processing services . Examples of such transactions are loan processing, \npeer-to-peer lending, payment processing, retirement recordkeeping, crowdfunding, \nbig data analytics, and investment management. \n• Environmental, social, and go vernance (ESG) metric services . Measuring, calculating, \nand otherwise assisting companies with ga thering and reporting their ESG metrics. \nTo be useful to report users, the description should clearly identify the services that are the \nfocus of the SOC 2 examination.  \nWhen handling personal information, a service organization may functio n in the role of a \ndata processor, data controller , or both. Depending on which of these roles the service organi-\nzation performs, its responsibilities with rega rd to protecting persona l information may dif-\nfer. Therefore, when the SOC 2 examination addr esses privacy, clear disclo sure of the role or \nroles performed by the service or ganization may be necessary to  describe the types of ser-\nvices provided. Such disclosures enable user s to understand how the se rvice organization ad-\ndressed its responsibilities to mitigate risks to the achieveme nt of its service commitments \nand system requirements related to privacy.  \nDC2:  The principal service commitments and sys-\ntem requirements A service organization adopts a mission and vision, sets strategies, and es tablishes objectives \nto help it meet its mission a nd vision based on its strategies . Management designs and imple-\nments individual systems to achie ve specific objectives and desi gns and implements controls \nwithin the system to mitigate the risks that th reaten the service organi zation’s achievement of \nthose objectives. The service organization’s objectiv es for its services an d the system used to \ndeliver those services are embodied in the serv ice commitments it makes to user  entities and \nthe requirements it establishes for the functioning of the system used to deliver those services \n(service commitments and system requirements). Disclosure of the principal service commit-\nments and system requirements en ables report users to understand the obj ectives that drive
Title: 2018 SOC 2 Description Criteria

Content: AICPA Guide SOC 2® Reporting on an Examination of Controls at a Servi ce Organization Relevant to  Security, Availability, Pro-\ncessing Integrity, Confidentiality, or Privacy  uses the term service auditor , rather than practitioner , to refer to a CPA reporting on \ncontrols at a service organization. Therefore, this document also uses the term service auditor .  \nfn 5 There are two types of SOC 2 examinations (type 1 and type 2), and the subject matters vary depending on which type of exami-\nnation the service auditor performs. The subject matters of a type 1 examination are ( a) the description and ( b) the suitability of the \ndesign of the controls to provide reasonable assurance that th e service organization’s service co mmitments and system requireme nts \nwould be achieved based on the applicable trust services cr iteria. The subject matters in a type 2 examination are ( a) the description, \n(b) the suitability of design of the controls to provide reasonab le assurance that the service organization’s service commitments  and \nsystem requirements would be achieved based on the applicable trust services criteria, and ( c) the operating effectiveness of controls \nto provide reasonable assurance that the service organization’s service commitments and system requirements were achieved based  on \nthe applicable trust services criteria. \nfn 6  This term refers to the trust se rvices criteria in TSP section 100, 2017 Trust Services Criteria for Security, Availability, Pro-\ncessing Integrity, Confidentiality, and Privacy (With Revised Points of Focus — 2022) , that pertain to the category or categories in-\ncluded within the scope of the particular examination. \nfn 7 Paragraph .A44 of AT-C section 105, Concepts Common to All Attestation Engagements .
Title: 2018 SOC 2 Description Criteria

Content: each criterion. This guidance does not address all possi ble situations; therefore,  users should carefully \nconsider the facts and circumstances  of the service organization and its  environment when applying the \ndescription criteria.  \n \nApplicability and Use of the Description Criteria \nSOC 2 Examination \n.03  The description criteria presented in this document were developed to be used in conjunction with the \nSOC 2 examination described in the AICPA Guide SOC 2© Reporting on an Examination of Controls at \na Service Organization Relevant to Security, Availab ility, Processing Integrity, Confidentiality, or Pri-\nvacy (guide). The SOC 2 examination is performed in accordance with AT-C section 105, Concepts \nCommon to All Attestation Engagements , and AT-C section 205, Assertion-Based  Examination \n \nfn 3 The 2017 Trust Services Criteria for Security, Availability, Pr ocessing Integrity, Confidentiality, and Privacy (With Revised \nPoints of Focus — 2022)  are codified in TSP section 100 in AICPA Trust Services Criteria .
Title: 2018 SOC 2 Description Criteria
=========
FINAL ANSWER: The five trust service principles of the SOC2 standard are Security, Availability, Processing Integrity, Confidentiality, and Privacy.
Title: 2018 SOC 2 Description Criteria

QUESTION: What’s the difference between privacy and confidentiality in SOC 2 criteria?
=========
Content: each criterion. This guidance does not address all possi ble situations; therefore,  users should carefully \nconsider the facts and circumstances  of the service organization and its  environment when applying the \ndescription criteria.  \n \nApplicability and Use of the Description Criteria \nSOC 2 Examination \n.03  The description criteria presented in this document were developed to be used in conjunction with the \nSOC 2 examination described in the AICPA Guide SOC 2© Reporting on an Examination of Controls at \na Service Organization Relevant to Security, Availab ility, Processing Integrity, Confidentiality, or Pri-\nvacy (guide). The SOC 2 examination is performed in accordance with AT-C section 105, Concepts \nCommon to All Attestation Engagements , and AT-C section 205, Assertion-Based  Examination \n \nfn 3 The 2017 Trust Services Criteria for Security, Availability, Pr ocessing Integrity, Confidentiality, and Privacy (With Revised \nPoints of Focus — 2022)  are codified in TSP section 100 in AICPA Trust Services Criteria .
Title: 2018 SOC 2 Description Criteria

Content: Page 17 Description Criteria fn 10 Implementation Guidance  \nWhen sensitive information is tr ansmitted through or resides in the system used to provide \nservices to users, the description may address th e confidentiality or privacy categories. In that \ncase, the description may also address the follo wing other matters about  the data component:  \n• The principal types of data created, collecte d, processed, transmitted, used, or stored by \nthe service organization and the methods used to collect, retain, disc lose, dispose of, or \nanonymize the data  \n• Personal information that warra nts security, data protection, or breach disclosures based \non laws or commitments (for example, persona lly identifiable information, protected \nhealth information, and payment card data) \n• Third-party entity informati on (for example, information su bject to confidentiality re-\nquirements in contracts) that warrants security, data prot ection, or breach  disclosures \nbased on laws or commitments \nFor each system component, such disclosures w ould generally address aspects of confidential \nand personal information used in providing the service within well-defi ned processes and in-\nformal ad hoc procedures. \nBoundaries of the system.  The description should clearly iden tify the system that is the focus \nof the SOC 2 examination. In some situations, however, it is not alwa ys clear whether a spe-\ncific activity or function performed  at the service organization is part of the system being de-\nscribed. Determining the functions or processes that are outside the boundaries of the system \nand describing them in the description may be necessary to prevent report users from misun-\nderstanding the boundaries of the sy stem. Therefore, if there is a risk that report users might \nbe confused about whether a sp ecific function or process is part of the system being de-\nscribed, the description needs to clearly identify  which processes or functions are outside the \nboundaries of the system  being described.   \nFor example, the following functions or processe s at the service organi zation may be outside \nthe boundaries of the system being described:
Title: 2018 SOC 2 Description Criteria

Content: AICPA Guide SOC 2® Reporting on an Examination of Controls at a Servi ce Organization Relevant to  Security, Availability, Pro-\ncessing Integrity, Confidentiality, or Privacy  uses the term service auditor , rather than practitioner , to refer to a CPA reporting on \ncontrols at a service organization. Therefore, this document also uses the term service auditor .  \nfn 5 There are two types of SOC 2 examinations (type 1 and type 2), and the subject matters vary depending on which type of exami-\nnation the service auditor performs. The subject matters of a type 1 examination are ( a) the description and ( b) the suitability of the \ndesign of the controls to provide reasonable assurance that th e service organization’s service co mmitments and system requireme nts \nwould be achieved based on the applicable trust services cr iteria. The subject matters in a type 2 examination are ( a) the description, \n(b) the suitability of design of the controls to provide reasonab le assurance that the service organization’s service commitments  and \nsystem requirements would be achieved based on the applicable trust services criteria, and ( c) the operating effectiveness of controls \nto provide reasonable assurance that the service organization’s service commitments and system requirements were achieved based  on \nthe applicable trust services criteria. \nfn 6  This term refers to the trust se rvices criteria in TSP section 100, 2017 Trust Services Criteria for Security, Availability, Pro-\ncessing Integrity, Confidentiality, and Privacy (With Revised Points of Focus — 2022) , that pertain to the category or categories in-\ncluded within the scope of the particular examination. \nfn 7 Paragraph .A44 of AT-C section 105, Concepts Common to All Attestation Engagements .
Title: 2018 SOC 2 Description Criteria

=========
FINAL ANSWER: The provided documents do not explicitly detail the difference between Privacy and Confidentiality within the SOC 2 criteria. However, based on general understanding and the context of SOC 2 examinations, Privacy typically refers to how personal information is collected, used, retained, disclosed, and disposed of, ensuring the rights of the data subject are protected. Confidentiality, on the other hand, focuses on protecting information from unauthorized access and disclosure, including data that may not be personal but is sensitive or proprietary in nature. Both principles are part of the Trust Services Criteria for SOC 2 examinations, emphasizing the importance of handling data with care to protect the interests of the service organization and its stakeholders. For a detailed explanation and differentiation of these principles according to SOC 2 criteria, one would need to consult the specific sections of the SOC 2 framework or guidelines that address Privacy and Confidentiality directly.
Title: 2018 SOC 2 Description Criteria

QUESTION: what can you do
=========
// doesn't matter what the sources are, ignore them
=========
FINAL ANSWER: This is a question-answering system over a corpus of IT compliance documents.

QUESTION: {question}
=========
{sources}
=========
FINAL ANSWER:"""  # noqa: E501

main = PromptTemplate(template=template, input_variables=["title", "question"])

per_source = PromptTemplate(
    template="Content: {page_content}\nTitle: {title}",
    input_variables=["page_content", "title"],
)
